config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  get 'ui(/:action)', controller: 'ui'

  resources :products, only: [:index, :new, :create, :edit, :update]
  resources :categories, only: [:show]

  resources :orders, only: [:show, :update]
  post '/submit_order', to: 'orders#submit'
  get '/order_confirmation', to: 'orders#confirm'

  resources :order_items, only: [:create, :update]

  resources :users, only: [:create]
  get '/register', to: 'users#new'
  get '/orders', to: 'users#orders', as: 'user_orders'


  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  get '/sign_out', to: 'sessions#destroy'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :product_categories
  has_many :products, through: :product_categories

  validates :title, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items
  belongs_to :user

  accepts_nested_attributes_for :order_items

  scope :sort_desc, -> { order('updated_at DESC') }

  def total
    subtotals = []
    order_items.each do |item|
      subtotals << item.subtotal
    end
    subtotals.inject(&:+)
  end
end#Order

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product

  validates :order,     presence: true
  validates :product,   presence: true
  validates :quantity,  numericality: { greater_than_or_equal_to: 0 }

  def subtotal
    self.quantity * product.price
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_categories
  has_many :categories, through: :product_categories

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" },
                            default_url: "stock_product.jpg"

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :title,         presence: true,
                            uniqueness: true

  validates :description,   presence: true

  validates :price,         presence: true,
                            numericality: { :greater_than_or_equal_to => 0 }
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders

  validates :name,      presence: true
  validates :email,     presence: true,
                        uniqueness: true

  has_secure_password validations: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?, :current_order

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    !!current_user
  end

  def current_order
    @current_order ||= Order.find(session[:order_id]) if session[:order_id]
  end

  def load_order
    @order = Order.find(session[:order_id])
  rescue ActiveRecord::RecordNotFound
    @order = Order.create(user: current_user, status: 'unsubmitted')
    session[:order_id] = @order.id
  end

  def require_user
    unless signed_in?
      flash[:info] = "Sorry, you'll need to log in to continue."
      redirect_to sign_in_path
    end
  end

  def require_order
    unless current_order
      flash[:danger] = "You need some items in your cart to continue."
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @products = @category.products
    render template: 'products/index'
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    load_order
    @order_item = @order.order_items.find_or_initialize_by(product_id: params[:product_id])
    @order_item.quantity += 1
    @order_item.save
    flash[:success] = 'Item added to cart.'
    redirect_to products_path
  end

  private

  def order_item_params
    params.require(:order_item).permit(
      :user_id,
      :product_id,
      )
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :require_order, only: [:submit]
  before_action :require_user, only: [:submit]

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])

    if params['update_cart']
      update_order_item_quantities
      flash[:success] = 'Your cart was updated.'
      redirect_to @order
    elsif params['empty_cart']
      delete_order
      flash[:info] = 'Your cart has been cleared out.'
      redirect_to root_path
    end
  end#update

  def submit
    if current_order.update(user: current_user, status: 'submitted')
      session[:order_id] = nil
      redirect_to order_confirmation_path
    else
      flash[:error] = 'Oops, something went wrong. Your order did not submit.'
      redirect_to :back
    end
  end

  def confirm
  end

  private

  def update_order_item_quantities
    order_items = params[:order][:order_items_attributes]

    order_items.each do |key, value|
      order_item = OrderItem.find(value['id'])
      if value['quantity'].to_i == 0
        order_item.destroy
      else
        order_item.update_attributes(quantity: value['quantity'].to_i)
      end
    end
  end

  def delete_order
    @order.destroy
    session[:order_id] = nil
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:success] = "You've successfully created a new product."
      redirect_to new_product_path
    else
      flash[:danger] = "Oops, something went wrong. Please fix the errors below."
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:success] = "The product was successfully updated."
      redirect_to products_path
    else
      flash[:danger] = "Oops, something went wrong. Please fix the errors below."
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:title,
                                    :description,
                                    :price,
                                    :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully signed in as #{user.name}"
      redirect_to products_path
    else
      flash[:danger] = "Oops, your email or password was incorrect. Please try again."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    session[:order_id] = nil 
    flash[:info] = "You have successfully signed out"
    redirect_to products_path
  end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController
  before_action do
    redirect_to :root if Rails.env.production?
  end

  layout "application"

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "You have successfully signed in as #{@user.name}."
      redirect_to products_path
    else
      flash[:danger] = "Oops, something went wrong. Please fix the errors below."
      render :new
    end
  end

  def orders
    @user = User.find(current_user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def product_count(order)
    if order
      count = 0
      order.order_items.each do |order_item|
        count = count + order_item.quantity
      end
      count
    else
      0
    end
  end

  def format_date(date)
    date.strftime('%a, %B %e, %Y')
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def print_price(price)
    number_to_currency(price)
  end
end

app/views/layouts/application.html.haml
!!! 5
%html(lang='en-us')
  %head
    %title First Bite by Cullen Jett
    %meta(charset="UTF-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")

    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %header
      = render 'shared/navigation'
    %section.main-content
      .container
        = render 'shared/messages'
        = yield

app/views/order_items/_order_item.html.haml
.row
  .col-sm-6
    %table.table
      %tr
        %th{width: '15%'}
        %th{width: '60%'} Name
        %th{width: '15%'} Price
        %th{width: '10%'} Qty
      %tr
        %td= image_tag order_item.product.image.url(:thumb), class: 'img-responsive'
        %td= order_item.product.title
        %td= order_item.product.price
        = form_for order_item do |f|
          %td= f.text_field :quantity

app/views/orders/confirm.html.haml
%h1 Confirm your order

app/views/orders/show.html.haml
.container-fluid
  = form_for @order do |f|
    .row
      .col-sm-8.col-sm-offset-2
        %h1.text-center Your Cart
        %table.table.table-striped.order-table
          %tr
            %th{width: '10%'}
            %th{width: '50%'} Item
            %th{width: '15%'} How many?
            %th{width: '15%'} Price
            %th{width: '10%'} Subtotal
          - @order.order_items.each do |order_item|
            %tr
              %td= image_tag order_item.product.image.url(:thumb), class: 'img-responsive'
              %td= order_item.product.title
              = f.fields_for :order_items, order_item do |i|
                %td= i.text_field :quantity, class: 'form-control'
              %td= order_item.product.price
              %td= print_price(order_item.subtotal)
          %tr
            %td
            %td
            %td
            %td Total:
            %td= print_price(@order.total)

        = f.submit "Empty Cart", name: 'empty_cart', class: 'btn btn-danger'
        = f.submit "Update Cart", name: 'update_cart', class: 'btn btn-info'
  .row
    .col-sm-8.col-sm-offset-2
      = button_to "Submit Order", submit_order_path, class: 'btn btn-success submit-order-button'

app/views/products/_form.html.haml
= bootstrap_form_for @product, :html => { :multipart => true } do |f|
  = f.text_field :title
  = f.text_area :description
  = f.text_field :price
  = f.file_field :image
  = f.form_group do
    = f.submit "#{button_content}", class: 'btn btn-block btn-primary'

app/views/products/_product.html.haml
.products.panel.panel-default
  .panel-body
    .row
      .col-xs-2
        = image_tag product.image.url, class: 'img-responsive img-rounded'
      .col-xs-6
        %p.panel-title= product.title
        %p.product-description= product.description
      .col-xs-2
        %p.product-price= print_price(product.price)
      .col-xs-2
        = button_to order_items_path(product_id: product.id), class: 'btn btn-success btn-sm' do
          %span.glyphicon.glyphicon-plus
          %span Add
        = link_to 'Edit', edit_product_path(product), class: 'btn btn-default btn-sm'

app/views/products/edit.html.haml
.container-fluid
  .row
    .col-sm-6.col-sm-offset-3
      %h1 Editing product
      = render 'form', button_content: 'Update Product'

app/views/products/index.html.haml
.row
  .col-sm-3.sidebar
    = render 'shared/sidebar'

  .col-sm-9
    .products-containter
      - @products.each do |product|
        = render 'products/product', product: product

app/views/products/new.html.haml
.container-fluid
  .row
    .col-sm-6.col-sm-offset-3
      %h1 New Product
      = render 'form', button_content: 'Create Product'

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-brand= link_to 'First Bite', root_path

    - if signed_in?
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            = "#{current_user.name}"
            %b.caret
          %ul.dropdown-menu
            %li
              = link_to 'Sign Out', sign_out_path
            %li
              = link_to 'Order History', user_orders_path
    - else
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to 'Register', register_path
        %li
          = button_to 'Sign In', sign_in_path, method: :get, class: 'navbar-btn btn btn-default'

app/views/shared/_sidebar.html.haml
.panel.panel-default
  .panel-heading
    %p.panel-title.text-center Your Cart
  .panel-body
    - if current_order
      %p= "You have #{product_count(current_order)} items in your cart."
      .panel-footer.checkout-box
        = link_to order_path(current_order), class: 'btn btn-default btn-block checkout-btn' do
          %span.glyphicon.glyphicon-shopping-cart
          %span= "Checkout (#{print_price(current_order.total)})"
    - else
      %p Your cart is empty.
      %p Add some items from the right to get started.


.panel.panel-default
  .panel-heading
    %p.panel-title.text-center Categories
  .panel-body
    %ul.nav.nav-pills.nav-stacked
      %li= link_to 'All', products_path, class: 'btn btn-default'
      - Category.all.each do |category|
        %li= link_to category.title, category_path(category), class: 'btn btn-default'

- if signed_in?
  .panel.panel-default
    .panel-heading
      %p.panel-title.text-center Admin
    .panel-body
      %ul.nav.nav-pills.nav-stacked
        %li= link_to 'Add Product', new_product_path, class: 'btn btn-default'

app/views/ui/front.html.haml
.container-fluid
  .jumbotron
    %h1.text-center First Bite
  .items-container
    - 10.times do
      = render 'shared/product_box'

app/views/ui/index.html.haml
%ul
  - Dir.glob('app/views/ui/*.html.haml').sort.each do |file|
    - wireframe = File.basename(file,'.html.haml')
    -  unless wireframe == 'index' || wireframe.match(/^_/)
      %li= link_to wireframe.titleize, action: wireframe unless wireframe == 'index'

app/views/users/new.html.haml
.container-fluid
  .row
    .col-sm-4.col-sm-offset-4
      %h1.text-center Register
      = bootstrap_form_for @user do |f|
        = f.text_field :name
        = f.email_field :email
        = f.password_field :password
        = f.form_group do
          = f.submit 'Sign Up', class: 'btn btn-block btn-primary'

app/views/users/orders.html.haml
%h1 Your orders
.row
  - @user.orders.sort_desc.each do |order|
    .col-sm-6
      .panel.panel-default
        .panel-heading
          %h3= format_date(order.updated_at)
          %p.status= order.status
        .panel-body
          %table.table.table-striped.order-table
            %tr
              %th{width: '50%'} Item
              %th{width: '15%'} How many?
              %th{width: '15%'} Price
              %th{width: '10%'} Subtotal
            - order.order_items.each do |order_item|
              %tr
                %td= order_item.product.title
                %td= order_item.quantity
                %td= order_item.product.price
                %td= print_price(order_item.subtotal)
            %tr
              %td
              %td
              %td Total:
              %td= print_price(order.total)